# Generated by Django 4.2.2 on 2023-07-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('tipo_doc', models.CharField(choices=[('TC', 'TIEMPO COMPLETO'), ('TH', 'TIEMPO HORARIO')], default='TC', max_length=2)),
                ('fecha_nac', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombree', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField(null=True)),
                ('procedencia', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo_mat', models.CharField(choices=[('T', 'TEORICO'), ('TP', 'TEORICO PRACTICO'), ('P', 'PRACTICO')], default='T', max_length=2)),
                ('habilitado', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('P', '1'), ('S', '2')], default='P', max_length=1)),
                ('gestion', models.PositiveIntegerField()),
                ('parcial_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcial_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcial_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('practicas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.docente')),
                ('id_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
                ('id_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.materia')),
            ],
        ),
    ]
